# https://wiki.archlinux.org/index.php/zsh#Simple_.zshrc
autoload -Uz compinit promptinit bashcompinit
compinit -u
promptinit
bashcompinit

zstyle ':completion:*' menu  select
prompt adam2

set -o histignore{space,alldups}

# https://wiki.archlinux.org/index.php/zsh#Fish-like_syntax_highlighting_and_autosuggestions
source ~/.config/zsh/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source ~/.config/zsh/zsh-vi-mode/zsh-vi-mode.plugin.zsh
# Always starting with insert mode for each command line
ZVM_LINE_INIT_MODE=$ZVM_MODE_NORMAL

alias yay=paru
alias g=git
alias ni=nvim
alias viss=vise
alias l='ls -AGFS'

# >>> mamba initialize >>>
# !! Contents within this block are managed by 'mamba init' !!
eval "$(~/bin/micromamba shell hook)"
# <<< mamba initialize <<<
# >>> umamba completion >>>
_umamba_completions()
{
  COMPREPLY=($(micromamba completer "${COMP_WORDS[@]:1}"))
}

complete -F _umamba_completions micromamba
# <<< umamba completion <<<
micromamba activate

# Created by `pipx`
# path+=~/.local/bin
# eval "$(pandoc --bash-completion)"
eval "$(luarocks path --bin)"
path+=~/.cargo/bin
# path+=~/doom-emacs/bin

source ~/.config/broot/launcher/bash/br
